// <auto-generated />
using System;
using System.Net;
using Aarogya.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aarogya.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AarogyaDbContext))]
    [Migration("20260219025610_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aarogya.Domain.Entities.AccessGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("GrantReason")
                        .HasColumnType("text")
                        .HasColumnName("grant_reason");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.Property<Guid>("GrantedToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_to_user_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("access_grant_status")
                        .HasDefaultValue("active")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("GrantedByUserId");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_access_grants_scope_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Scope"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Scope"), new[] { "jsonb_path_ops" });

                    b.HasIndex("GrantedToUserId", "Status")
                        .HasDatabaseName("ix_access_grants_granted_to_status");

                    b.HasIndex("PatientId", "GrantedToUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_access_grants_active")
                        .HasFilter("status = 'active'");

                    b.HasIndex("PatientId", "Status")
                        .HasDatabaseName("ix_access_grants_patient_status");

                    b.ToTable("access_grants", null, t =>
                        {
                            t.HasCheckConstraint("access_grants_not_self_chk", "patient_id <> granted_to_user_id");

                            t.HasCheckConstraint("access_grants_revoked_time_chk", "revoked_at IS NULL OR revoked_at >= starts_at");

                            t.HasCheckConstraint("access_grants_time_window_chk", "expires_at IS NULL OR expires_at > starts_at");
                        });
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("ActorRole")
                        .HasColumnType("user_role")
                        .HasColumnName("actor_role");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<IPAddress>("ClientIp")
                        .HasColumnType("inet")
                        .HasColumnName("client_ip");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entity_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("RequestMethod")
                        .HasColumnType("text")
                        .HasColumnName("request_method");

                    b.Property<string>("RequestPath")
                        .HasColumnType("text")
                        .HasColumnName("request_path");

                    b.Property<int?>("ResultStatus")
                        .HasColumnType("integer")
                        .HasColumnName("result_status");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.HasKey("Id");

                    b.HasIndex("Details")
                        .HasDatabaseName("ix_audit_logs_details_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Details"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Details"), new[] { "jsonb_path_ops" });

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_logs_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_actor_time");

                    b.HasIndex("EntityType", "EntityId", "OccurredAt")
                        .HasDatabaseName("ix_audit_logs_entity_time");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("audit_logs_result_status_chk", "result_status IS NULL OR (result_status BETWEEN 100 AND 599)");
                        });
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.EmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<byte[]>("NameEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("name_encrypted");

                    b.Property<byte[]>("PhoneEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("phone_encrypted");

                    b.Property<byte[]>("PhoneHash")
                        .HasColumnType("bytea")
                        .HasColumnName("phone_hash");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("relationship");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PhoneHash")
                        .HasDatabaseName("ix_emergency_contacts_phone_hash");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ux_emergency_contacts_primary_per_user")
                        .HasFilter("is_primary");

                    b.ToTable("emergency_contacts", (string)null);
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ChecksumSha256")
                        .HasColumnType("text")
                        .HasColumnName("checksum_sha256");

                    b.Property<DateTimeOffset?>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<string>("FileStorageKey")
                        .HasColumnType("text")
                        .HasColumnName("file_storage_key");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("ReportNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("report_number");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("report_type")
                        .HasColumnName("report_type");

                    b.Property<DateTimeOffset?>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<string>("Results")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("results");

                    b.Property<string>("SourceSystem")
                        .HasColumnType("text")
                        .HasColumnName("source_system");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("report_status")
                        .HasDefaultValue("uploaded")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<Guid>("UploadedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("Metadata")
                        .HasDatabaseName("ix_reports_metadata_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Metadata"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Metadata"), new[] { "jsonb_path_ops" });

                    b.HasIndex("ReportNumber")
                        .IsUnique();

                    b.HasIndex("Results")
                        .HasDatabaseName("ix_reports_results_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Results"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Results"), new[] { "jsonb_path_ops" });

                    b.HasIndex("UploadedByUserId");

                    b.HasIndex("PatientId", "UploadedAt")
                        .HasDatabaseName("ix_reports_patient_uploaded_at");

                    b.HasIndex("ReportType", "ReportedAt")
                        .HasDatabaseName("ix_reports_type_reported_at");

                    b.HasIndex("Status", "UploadedAt")
                        .HasDatabaseName("ix_reports_status_uploaded_at");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("reports_time_order_chk", "reported_at IS NULL OR collected_at IS NULL OR reported_at >= collected_at");
                        });
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.ReportParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsAbnormal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_abnormal");

                    b.Property<decimal?>("MeasuredValueNumeric")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("measured_value_numeric");

                    b.Property<string>("MeasuredValueText")
                        .HasColumnType("text")
                        .HasColumnName("measured_value_text");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parameter_code");

                    b.Property<string>("ParameterName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parameter_name");

                    b.Property<string>("RawParameter")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_parameter");

                    b.Property<string>("ReferenceRangeText")
                        .HasColumnType("text")
                        .HasColumnName("reference_range_text");

                    b.Property<Guid>("ReportId")
                        .HasColumnType("uuid")
                        .HasColumnName("report_id");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("MeasuredValueNumeric")
                        .HasDatabaseName("ix_report_parameters_value_numeric")
                        .HasFilter("measured_value_numeric IS NOT NULL");

                    b.HasIndex("ParameterName")
                        .HasDatabaseName("ix_report_parameters_name");

                    b.HasIndex("RawParameter")
                        .HasDatabaseName("ix_report_parameters_raw_parameter_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RawParameter"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("RawParameter"), new[] { "jsonb_path_ops" });

                    b.HasIndex("ReportId")
                        .HasDatabaseName("ix_report_parameters_report_id");

                    b.HasIndex("ReportId", "ParameterCode")
                        .IsUnique();

                    b.ToTable("report_parameters", (string)null);
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AadhaarRefToken")
                        .HasColumnType("uuid")
                        .HasColumnName("aadhaar_ref_token");

                    b.Property<byte[]>("AadhaarSha256")
                        .HasColumnType("bytea")
                        .HasColumnName("aadhaar_sha256");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<byte[]>("EmailEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("email_encrypted");

                    b.Property<byte[]>("EmailHash")
                        .HasColumnType("bytea")
                        .HasColumnName("email_hash");

                    b.Property<string>("ExternalAuthId")
                        .HasColumnType("text")
                        .HasColumnName("external_auth_id");

                    b.Property<byte[]>("FirstNameEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("first_name_encrypted");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<byte[]>("LastNameEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("last_name_encrypted");

                    b.Property<byte[]>("PhoneEncrypted")
                        .HasColumnType("bytea")
                        .HasColumnName("phone_encrypted");

                    b.Property<byte[]>("PhoneHash")
                        .HasColumnType("bytea")
                        .HasColumnName("phone_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("user_role")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AadhaarSha256")
                        .HasDatabaseName("ix_users_aadhaar_sha256");

                    b.HasIndex("EmailHash")
                        .HasDatabaseName("ix_users_email_hash");

                    b.HasIndex("ExternalAuthId")
                        .IsUnique();

                    b.HasIndex("PhoneHash")
                        .HasDatabaseName("ix_users_phone_hash");

                    b.HasIndex("Role", "IsActive")
                        .HasDatabaseName("ix_users_role_active");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("users_gender_chk", "gender IS NULL OR gender IN ('male', 'female', 'other', 'unknown')");
                        });
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.AccessGrant", b =>
                {
                    b.HasOne("Aarogya.Domain.Entities.User", "GrantedByUser")
                        .WithMany("CreatedAccessGrants")
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aarogya.Domain.Entities.User", "GrantedToUser")
                        .WithMany("GrantedAccessGrants")
                        .HasForeignKey("GrantedToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aarogya.Domain.Entities.User", "Patient")
                        .WithMany("PatientAccessGrants")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GrantedByUser");

                    b.Navigation("GrantedToUser");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Aarogya.Domain.Entities.User", "ActorUser")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.EmergencyContact", b =>
                {
                    b.HasOne("Aarogya.Domain.Entities.User", "User")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.Report", b =>
                {
                    b.HasOne("Aarogya.Domain.Entities.User", "Doctor")
                        .WithMany("DoctorReports")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Aarogya.Domain.Entities.User", "Patient")
                        .WithMany("PatientReports")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aarogya.Domain.Entities.User", "UploadedByUser")
                        .WithMany("UploadedReports")
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.ReportParameter", b =>
                {
                    b.HasOne("Aarogya.Domain.Entities.Report", "Report")
                        .WithMany("Parameters")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.Report", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("Aarogya.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("CreatedAccessGrants");

                    b.Navigation("DoctorReports");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("GrantedAccessGrants");

                    b.Navigation("PatientAccessGrants");

                    b.Navigation("PatientReports");

                    b.Navigation("UploadedReports");
                });
#pragma warning restore 612, 618
        }
    }
}
