// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Aarogya.Infrastructure.Persistence.Migrations;

/// <inheritdoc />
public partial class AddAadhaarVaultUserForeignKey : Migration
{
  /// <inheritdoc />
  protected override void Up(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.CreateIndex(
      name: "IX_users_aadhaar_ref_token",
      table: "users",
      column: "aadhaar_ref_token");

    migrationBuilder.AddForeignKey(
      name: "FK_users_aadhaar_records_aadhaar_ref_token",
      table: "users",
      column: "aadhaar_ref_token",
      principalSchema: "aadhaar_vault",
      principalTable: "aadhaar_records",
      principalColumn: "reference_token",
      onDelete: ReferentialAction.SetNull);
  }

  /// <inheritdoc />
  protected override void Down(MigrationBuilder migrationBuilder)
  {
    migrationBuilder.DropForeignKey(
      name: "FK_users_aadhaar_records_aadhaar_ref_token",
      table: "users");

    migrationBuilder.DropIndex(
      name: "IX_users_aadhaar_ref_token",
      table: "users");
  }
}
